// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ2cWEQaawFqX2eMoLg_o9A-OQvWmtkbU',
    appId: '1:364396842288:web:2e5aa329af34ed61968cf5',
    messagingSenderId: '364396842288',
    projectId: 'furniture-e6046',
    authDomain: 'furniture-e6046.firebaseapp.com',
    storageBucket: 'furniture-e6046.appspot.com',
    measurementId: 'G-T0RZBPXT5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWp1zvpGK0erk2QRyucp195iXm4ceVdvs',
    appId: '1:364396842288:android:d259a0b9c60a7437968cf5',
    messagingSenderId: '364396842288',
    projectId: 'furniture-e6046',
    storageBucket: 'furniture-e6046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6oaaZXRDcZ5ho_lkxkQvHarOmjRGtBBk',
    appId: '1:364396842288:ios:f9109da746ae76c7968cf5',
    messagingSenderId: '364396842288',
    projectId: 'furniture-e6046',
    storageBucket: 'furniture-e6046.appspot.com',
    iosBundleId: 'com.example.furniture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6oaaZXRDcZ5ho_lkxkQvHarOmjRGtBBk',
    appId: '1:364396842288:ios:106717c43c3046ce968cf5',
    messagingSenderId: '364396842288',
    projectId: 'furniture-e6046',
    storageBucket: 'furniture-e6046.appspot.com',
    iosBundleId: 'com.example.furniture.RunnerTests',
  );
}
